name: Build And Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs: 
  buildAndTest:
    runs-on: ubuntu-latest

    env:
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
      
      - name: Install dependencies
        run: dotnet restore
        
      - name: Initialize Testing Stack
        run: docker-compose up -d
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
      
      - name: Test
        run: dotnet test --no-restore
